### ISSUE TITLE
Adding data

### ISSUE THREAD

**Issue by macaba** [pavel212/noise#1]
Hi,

I have captured data from ADA4523, what processing do I need to do to get a dat file that I can plot using your gnuplot scripts?

I did some of my own processing but I don't think it's in the correct units.

![image](https://user-images.githubusercontent.com/1031306/182032392-f5e08ddf-5561-4106-9b60-a047c44e0179.png)

**Comment by pavel212** [comment]
You plotted spectral noise density, which is a normal way to characterize noise.
but makes it a bit more tricky to answer what would be RMS noise if i would average measurements over N seconds, as you need to integrate your noise density over frequency range and also averaging itself has a frequency characteristic with 20dB/decade with notches at N/"averaging time". So i just measured RMS noise directly.
Data in repository is measured RMS voltage integral noise [in V*seconds] vs integration time, RMS for 10 samples.

Voltage integral instead of voltage was done for purpose as compared voltmeters were mainly used for inductive magnetic measurements, when coils or stretched wires (single loop coil) is moved in magnetic field and induced voltage is proportional to flux derivative, so to get the magnetic field you need to integrate the voltage.
But there is also a second plot which is Voltage noise vs "averaging" time, which basically the same plot, using the same data but values divided by horizontal scale.

If you have sampled voltage vs time data:
calculate 10 sums of K samples 1 to K,  (K+1) to 2K, (2K+1) to 3K ...  9K+1 to 10K, 
calculate standard deviation of this 10 sums, and divide it by sampling frequency Fs you would get RMS voltage integral noise, and this would correspond to K/Fs integration time.
Now vary K from 1 to Length/10 to get the data for gnuplot scripts.

**Comment by macaba** [comment]
Thank you for the explanation, that is very helpful.

I will write an algorithm to implement what you suggested and hopefully post back here with a chart containing ADA4523 data. I'm happy to contribute the .dat file to this repository too.

**Comment by macaba** [comment]
I captured more data, it is available here:
https://github.com/macaba/noise/tree/main/data

This is the NSD of the data:
![image](https://user-images.githubusercontent.com/1031306/182958811-f74d3478-ba44-4c0c-ad99-515973ff8e3b.png)

I came up with two different interpretations of the algorithm you described and plotted the resulting data:
![integrators_v2](https://user-images.githubusercontent.com/1031306/182958880-768e741b-7dd3-4584-9164-6a29cc8b008f.png)

Please could you use my source data from the link above, process it & plot so I can see if one of my algorithms is correct?

**Comment by pavel212** [comment]
_2 looks correct
![image](https://user-images.githubusercontent.com/7340070/183298939-7d73dae9-7212-4672-93d0-2b3bde2acf77.png)
![image](https://user-images.githubusercontent.com/7340070/183299256-68711f2d-8a4f-47fd-b834-9df3035051a2.png)

0.025	6.095108306626686e-10
0.05	1.0711836120948113e-9
0.075	1.1664088759607094e-9
0.1	1.0015812499853206e-9
0.125	7.103333702866353e-10
0.15	1.3985378206560785e-9
0.175	1.1578653886064767e-9
0.2	1.4660364434673475e-9
0.225	1.438561872370783e-9
0.25	1.5327152850436801e-9
0.275	1.6138449941680363e-9
0.3	1.917859681751118e-9
0.325	1.883711209020136e-9
0.35	1.8744097815910304e-9
0.375	2.185925611387809e-9
0.4	2.3393965552430576e-9
0.425	1.7445187951569792e-9
0.45	2.0961307484432247e-9
0.5	1.9944955152840576e-9
0.525	2.055174263543668e-9
0.575	2.3027017607674407e-9
0.60	2.4013564644503496e-9
0.65	2.609123928184123e-9
0.70	2.2320719825454017e-9
0.75	2.264242240104708e-9
0.8	2.2507962312295486e-9
0.85	3.0858420709942315e-9
0.925	3.5964996087639302e-9
0.975	3.189772957320542e-9
1.05	3.7525520458049495e-9
1.125	1.9672429676214075e-9
1.225	2.9177594975426907e-9
1.3	3.9767385193674315e-9
1.40	4.641331925106528e-9
1.5	4.805767827457169e-9
1.6	3.747911367292449e-9
1.725	6.4145199647744035e-9
1.85	3.982507864686422e-9
1.975	5.601121955748632e-9
2.1	5.9187094889390285e-9
2.275	6.3613774880100115e-9
2.425	5.832933787391622e-9
2.6	5.6527639926199925e-9
2.775	6.480492793486059e-9
2.975	6.765679694868192e-9
3.2	4.905159787935952e-9
3.425	6.842758406309977e-9
3.675	6.491598988521377e-9
3.95	6.048605460622629e-9
4.225	7.604801550815782e-9
4.525	6.438390221573808e-9
4.85	7.721792363903358e-9
5.2	6.7189187776873616e-9
5.575	7.199394687459203e-9
5.975	9.215679026501601e-9
6.4	7.839366000330744e-9
6.85	6.62765042025186e-9
7.35	8.867948317927673e-9
7.875	8.543039948771011e-9
8.45	1.0915865043952614e-8
9.05	1.1678234417129837e-8
9.7	1.396982407039936e-8
10.4	1.4639663166993147e-8
11.15	1.7466620316233466e-8
11.95	2.077411023961092e-8
12.8	2.0493377584071944e-8
13.725	2.3009638779668473e-8
14.7	2.5909233499158487e-8
15.75	2.648233890166852e-8
16.9	2.9092434200657426e-8
18.1	2.9049142794981965e-8
19.4	3.081154916893059e-8
20.8	3.1421471038345666e-8
22.275	3.252427977103411e-8
23.875	3.27344173473946e-8
25.6	3.4923576377593463e-8
27.425	3.952912868470059e-8
29.4	4.4203013480353215e-8
31.525	3.907207094549196e-8
33.775	4.103752587977251e-8
36.2	3.9871531819849325e-8
38.8	4.556803406485455e-8
41.575	5.06598396212939e-8
44.575	5.080332591282495e-8
47.775	5.410427279516736e-8
51.2	5.674894331555561e-8
54.875	5.526193214450477e-8
58.825	5.1691768981106526e-8
63.025	7.140855761458271e-8
67.55	5.918604920786767e-8
72.4	7.845328629037531e-8
77.6	6.325822952400196e-8
83.175	8.470628355271334e-8
89.15	7.592332391921739e-8
95.55	7.538126402472038e-8
102.4	6.951104021301749e-8
109.75	6.376489451631787e-8
117.625	7.652263753989352e-8
126.075	1.1161986063147982e-7
135.125	1.0605575541504533e-7
144.825	1.2256412299276182e-7
155.2	1.1050526200930391e-7
166.35	1.2506748645820785e-7
178.3	1.3443220907648132e-7
191.075	1.55019846338612e-7
204.8	1.4203111940752213e-7
219.5	2.1048470031170454e-7
235.25	1.718712647236301e-7
252.15	2.1894393527746074e-7
270.225	1.9373703461551817e-7
289.625	2.4756017714065076e-7
310.425	1.9145771573771733e-7
332.7	2.481240366332267e-7
356.575	2.510334136787126e-7
382.175	2.4889789126365154e-7
409.6	3.385447936456525e-7
439.	2.1205708663881179e-7
470.5	3.4165216789981794e-7
504.275	3.555271457440042e-7
540.475	3.349679830495046e-7
579.25	3.450079943079948e-7
620.85	3.134029686184071e-7
665.4	3.736942915670631e-7
713.15	4.798386780566337e-7
764.35	4.625587163689321e-7
819.2	5.017799633369329e-7
878.	6.523880458698166e-7
941.025	1.3645787466448002e-6
1008.55	1.4166944410910058e-6
1080.95	1.420047257174088e-6
1158.525	1.4849160609289777e-6
1241.675	1.584795025861391e-6
1330.8	1.5026708138856042e-6
1426.3	1.6795127305520558e-6
1528.675	1.4306713979272673e-6
1638.4	1.987081719197996e-6
1756.	2.23772913286398e-6
1882.025	2.573293593935486e-6
2017.1	3.065550786916652e-6
2161.875	2.99883106488792e-6
2317.05	3.105320366829873e-6
2483.35	3.252966781925362e-6
2661.6	3.80643750241277e-6
2852.625	4.382402168974721e-6
3057.375	5.158500125681842e-6
3276.8	5.331570007420751e-6

**Comment by macaba** [comment]
Good to know - I've adjusted it and get a very similar line. (average of 10 plot)

![integrators_v2](https://user-images.githubusercontent.com/1031306/183300178-eaa7964b-d532-46a0-b82e-511ef42ff7e6.png)

As my datalog is very long, that gave me the ability to try an average of 50. It looks like the white noise region is perfect for both averaging modes, but where there is significant 1/f noise they don't match anymore (3*10^1 to 10^3).

Maybe I should try converting my noise density result into RMS/integration time data?

**Comment by pavel212** [comment]
making stdev over 50 or even more "samples" adds more 1/f noise from lower frequencies. as now with e.g. 1 second averaging you also include some drifts that happen on 50 sec time scale. that's why it goes up at longer integration time.
2 sample Allan deviation could probably also be a better approach.
And also if you reverse frequency axis of NSD to convert it to time and multiply with sqrt(f) to get volts instead of proper integration, you would get quite similar smooth curve.

but just stdev over 10 samples gives you direct answer on "what would be RMS error value if i would measure something 10 times at given integration time", which i usually do. Without any additional conversion. And despite it is not absolutely clean and mathematically correct way to characterize noise.

**Comment by macaba** [comment]
That makes sense, thanks for explaining. It’s a quick and approximate way to compare devices.

**Comment by macaba** [comment]
Good suggestion about converting NSD, it looks good.

![integrators_v2](https://user-images.githubusercontent.com/1031306/183309929-13f2553f-e53b-497d-b7f8-50c9f37fcc00.png)
